# Generated by Django 5.1.2 on 2024-10-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('persona', models.CharField(choices=[('F', 'Persona Fisica'), ('M', 'Persona Moral')], max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('energetico', 'ENERGETICO'), ('inmobiliario', 'INMOBILIARIO'), ('materiales', 'MATERIALES'), ('industrial', 'INDUSTRIAL'), ('consumonobasico', 'BIENES DE CONSUMO NO BÁSICO'), ('consumofrecuente', 'PRODUCTOS DE CONSUMO FRECUENTE'), ('salud', 'SALUD'), ('financiero', 'SERVICIOS FINANCIEROS'), ('tecnologia', 'TECNOLOGIA DE LA INFORMACION'), ('telecomunicaciones', 'TELECOMUNICACIONES'), ('otro', 'OTRO')], max_length=50)),
                ('pais', models.CharField(choices=[('1', 'México'), ('2', 'EUA'), ('3', 'Colombia'), ('4', 'Argentina'), ('5', 'Chile')], max_length=2)),
                ('acercad', models.TextField()),
            ],
        ),
    ]
