# Generated by Django 5.1.6 on 2025-03-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('CEO', 'CEO / Fundador'), ('CFO', 'CFO / Finanzas'), ('Contralor', 'Contralor Financiero'), ('Analista', 'Analista Financiero'), ('Otro', 'Otro')], max_length=50)),
                ('employees', models.CharField(choices=[('1-10', '1 - 10'), ('11-50', '11 - 50'), ('51-200', '51 - 200'), ('201-500', '201 - 500'), ('501-1000', '501 - 1000'), ('1000+', 'Más de 1000')], max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
